package com.example.pi.models;

public class QuestionsRH {

    public static String question[] = {
            ///Perguntas
            "O que é um mapa mental?",
            "Oque é um organograma?",
            "São tipos de recrutamento e seleção:",
            "Qual a jornada de trabalho de um Jovem Aprendiz?",
            "Qual a idade do jovem Aprendiz?",
            "As leis trabalhistas sempre foram as mesmas?",
            "Do que se trata a Legislação Trabalhista?",
            "Quando a Previdência surgiu?",
            "Onde a Previdência surgiu?",
            "Qual foi o objetivo da Reforma Trabalhista?",
            "Quais os tipos de relação de trabalho?",
            "O que é direitos trabalhistas?",
            "Todos são direitos dos trabalhadores, exceto?",
            "Quando deve ser feito o pagamento das férias ao empregado?",
            "O empregado é obrigado a dar intervalo de almoço?",
            "Quando o empregado adquire direito às férias? ",
            "Quando o pagamento das férias deve ser feito?",
            "Quem define  a data das férias do empregado?",
            "O que é SST",
            "Qual a função da CTPS?",
            "Qual o prazo para entrar com a ação trabalhista?",
            "O que é DSR?",
            "Minhas férias poderão ser convertidas em abono pecuniário?",
            "O que é GGP?",
            "Quando as férias deverão ser pagas?",
            "Depois de quantos meses trabalhados as férias devem ser concedidas ao colaborador?",
            "Qual o período mínimo para fazer a  solicitação das férias?",
            "Qual o valor máximo que pode ser pago ao INSS?\n",
            "Qual o valor do INSS de um trabalhador que recebe um salário mínimo?",
            "Qual a porcentagem de desconto do salário,caso o colaborador queira o vale-transporte?",
            "Qual o significado da sigla IRRF?",
            "O que salário Líquido?",
            "Qual o percentual de FGTS pago ao colaborador demitido sem justa causa?",
            "Quais são os valores das alíquotas do INSS?",
            "Com quantos dias de falta o colaborador  perde seu direito total às férias? ",
            "O que significa a sigla DSR?",
            "Qual o significado da sigla INSS?",
            "Quantos dias temos de direito às férias?",
            "Quando temos direito a DSR?",
            "Após quanto tempo de trabalho o colaborador tem direito às férias?",
            "Quais são os graus de insalubridade?",
            "Quando recebemos o 13°?",
            "Existe quantos grau de insalubridade? ",
            "Quais os impostos que incidem sobre 13°?",
            "Por que o FGTS foi criado?",
            "Quando foi criada a CLT?",
            "Qual o Presidente sancionou a CLT?",
            "A respeito da Constituição de 1988, também conhecida como Constituição Cidadã , selecione a alternativa incorreta:",
            "Observada a regra do artigo 451 da CLT , o contrato de trabalho por prazo determinado não poderá ser estipulado por mais de:",
            "O contrato de experiência é uma modalidade de contrato por prazo determinado. Sua finalidade é verificar se o empregado tem aptidão para exercer a função para a qual foi contratado. \n Esse tipo de contrato deverá ser de:",
            "Quando foi criada a CBO?",
            "O que é análise swot?",
            "Benchmarking significa?",
            "O que é organograma?",
            "O que é mapeamento de processos?",
            "O que é Treinamento e Desenvolvimento?",
            "O treinamento serve para? ",
            "Quais os principais tipos de treinamento e desenvolvimento de pessoas?",
            "O que significa T e D?",
            "Qual a área que é responsável por realizar T e D?",
            "O que faz um profissional de treinamento?",
            "O que é hard skill?",
            "Qual a importância de treinar a equipe?",
            "Qual o motivo para motivar uma equipe?",
            "Principais tópicos de um currículo",
            "Seu superior te dá uma mesa cheia de papelada para ser preenchida em 4 horas, como você agiria?",
            "Forma de um colaborador se comportar de acordo com as experiências pessoais de vida dele?",
            "Como identificar de maneira ética e imediata, o cargo do colaborador?",
            "Na estrutura da entrevista, marque a alternativa que traz a função de cada participante?",
            "Documento pessoal em que ficam registrados todos os contratos de trabalho e experiências profissionais? ",
            "Qual é o principal benefício para a organização ao realizar a entrevista coletiva?",
            "Qual o principal objetivo da dinâmica em grupo?",
            "Qual o principal objetivo de uma entrevista em grupo?",
            "São tipos de comportamentos corretos durante a entrevista coletiva, exceto:",
            "Qual ferramenta está sendo utilizada na atualidade para facilitar e modernizar as entrevistas de emprego?",
            "O que é necessário para fazer um vídeo currículo?",
            "Qual a finalidade do vídeo currículo?",
            "O que é o pitch?",
            "Onde surgiu a expressão pitch?"

    };

    public static String choices[][] = {
            ///escolhas
            {"Um tipo de mapeamento para recrutar pessoas", "É um teste mental usado pelas organizações com seus colaboradores", "São diagramas que relacionam diferentes informações a uma fonte central", "Uma técnica de vendas"},
            {"Ilustra as etapas, sequências e decisões de um processo ou fluxo de trabalho", "Uma ilustração estratégica com o intuito de auxiliar clientes", "É uma representação gráfica da divisão hierárquica e da relação superior-subordinado", "Um gráfico com todos colaboradores de determinada organização"},
            {"Externo, interno e misto", "Interno, simulado, não estruturado", "Externo, coletivo, estruturado", "Interno, teórico, misto"},
            {"Para os aprendizes que estão cursando o ensino fundamental será seis horas diárias.Já para os que completaram o ensino médio será até 8 horas diárias", "Para os aprendizes que estão cursando o ensino fundamental será uma carga horária de 8 horas. Já os que completaram o ensino médio será de 6 horas diárias", "Varia dependendo da idade do aprendiz", "8 horas diárias"},
            {"13 a 23 anos", "14 a 18 anos", "15 a 21 anos", "14 a 24 anos"},
            {"Sim, as leis trabalhistas nunca foram alteradas desde sua criação", "Não, com a reforma trabalhista vieram mais de 100 mudanças", "Não, houveram poucas mudanças", "Sim, sempre foram eficazes"},
            {"Trata-se de normas legais com o objetivo de orientar os condutores garantindo a segurança dos veículos", "Trata-se do empregador ter mais poder sobre o empregado", "É o documento legal que da subsidios ao empregado para sobrepor-se ao empregador", "A legislação trata sobre os direitos para com a proteção da saúde do colaborador"},
            {"Surgiu em 1833", "Surgiu em 1943", "Surgiu em 1832", "Surgiu em 2000"},
            {"Inglaterra", "Portugal", "Suiça", "Alemanha"},
            {" Igualar os direitos de ambos lados", "Combater o desemprego gerado pela crise econômica", "Dar mais voz ao empregador sobre o colaborador", "Ajudar os trabalhadores"},
            {"Remunerada", "Remunerada ou obrigatoria", "Remunerada ou então voluntária", "Obrigatória "},
            {"São leis e regras que regem a relação entre colaboradores e empregadores", "São leis e regras que não regem a relação entre colaboradores e empregadores", "São leis que cabe ao colaborador seguir ou não", "São leis dirigidas apenas para os empregadores"},
            {"Salário mínimo", "Carteira de trabalho assinada", "Repouso semanal remunerado", "Folga em todos os feriados"},
            {"Deve ser pago quando empregado voltar de suas férias ", "Deve ser pago 10 dias antes de sair de férias", "Deve ser pago 2 dias antes de sair de férias", "Deve ser pago no começo do mês que ele entrar de férias"},
            {"Sim, independente de quantas horas ele trabalhou", "Sim, para os trabalhadores com jornada superior à 6 horas diária é obrigatório o intervalo mínimo de 1hora de almoço", "Não, ele pode trabalhar as 8 horas somente com 15 minutos de café", "É de sua escolha"},
            {"Após 8 meses trabalhados", "Após 12 meses trabalhados", "Após 2 anos trabalhados", "Após 5 meses trabalhados"},
            {"1 semana antes do início das férias", "30 dias depois das férias ", "8 dias antes do início das férias", "2 dias antes do início das férias"},
            {"o empregador é quem define ", "recursos humanos ", "o colaborador", "o colega de serviço"},
            {"sistema social de trabalho", "serviço de segurança do trabalho", "Segurança e saúde do trabalho", "saúde da sociedade no trabalho"},
            {"Documento que comprova o vínculo legal entre um empregador e um colaborador", "Documento que comprova  acidente de trabalho", "Documento necessário para assinar carteira de motorista", "Documento para receber rescisão"},
            {"Até no máximo 12 meses", "Até no máximo 1 ano", "Até no máximo 2 anos", "Até no máximo 1 ano e 6 meses"},
            {"Documento  semanal Recursos Humanos", "Descanso Semanal Remunerado", "Defensoria Social de Rendas", "Desconto Social de Renda"},
            {"Poderão ser convertidos em apenas 6 dias", "Poderão ser convertidos em apenas 4 dias", "Poderão ser convertidos em apenas 8 dias", "Poderão ser convertidos em apenas 10 dias"},
            {"Gestão Gerencial de Posse", "Gerência de Gestão Pessoal", "Gerência de Gestão de Pessoas", "Grupo de Gestão de Pagamento"},
            {"No máximo, até 2 dias úteis antes do início do período de descanso", "No máximo, até 5 dias úteis antes do início do período de descanso", "No máximo, até 8 dias úteis antes do início do período de descanso", "No máximo, até 3 dias úteis antes do início do período de descanso"},
            {"10 meses", "12 meses", "6 meses", "8 meses"},
            {"15 dias", "3 semanas", "30 dias", "5 semanas"},
            {"828,00 R$", "838,28 R$", "828,28 R$", "828,38 R$"},
            {"1212,00 R$", "12,12 R$", "90,90 R$", "84,84 R$"},
            {"6 %", "5 %", "10 %", "3 %"},
            {"Imposto de Renda Retirado da Fonte", "Imposto de Renda Retido na Fonte", "Instituição das Rendas Regionais e Federais", "Imposto Regional Retirado da Fonte"},
            {"É o salário recebido mensalmente pelo colaborador", "É o salário mais os benefícios recebido pelo colaborador", "É a soma do salário e dos benefícios recebido pelo colaborador menos os descontos", "São os benefícios recebidos pelo colaborador"},
            {"50 %", "40 %", "30 %", "25 %"},
            {"9, 12, 15 e 18 %", "7,5, 9, 10,5 e 12 %", "7,5, 9, 12 e 14%", "7,5, 12, 15 e 20 %"},
            {"A partir de 28 faltas ", "A partir de 30 faltas", "A partir de 32 faltas", "A partir de 35 faltas"},
            {"Descanso Semanal Remunerado", "Dias da Semana Remunerado", "Dias Sem Remuneração", "Descanso Sem Remuneração"},
            {"Instituto Nacional Serviço Social", "Instituto Nacional do Servidor Social ", "Instituto Nacional do Seguro Social", "Instituto Nacional Seguro do Servidor"},
            {"40 dias", "30 dias", "20 dias", "15 dias"},
            {"A cada 05 dias trabalhados", "A cada 10 dias trabalhados", "A cada 03 dias trabalhados", "A cada 07 dias trabalhados"},
            {"12 Meses de prestação de serviço", "5 Meses de prestação de serviço", "10 Meses de prestação de serviço", "3 Meses de prestação de serviço"},
            {"10%, 20% e 40%", "30%, 40% e 50%", "05%, 10% e 15%", "20%, 35% e 50%"},
            {"A primeira de 1° de janeiro e 1° de dezembro; e a segunda até 30 de dezembro", "A primeira entre 20 de fevereiro e 20 de novembro; e a segunda até 20 de janeiro", "A primeira entre 1° de janeiro e 30 de outubro; e a segunda até 20 de novembro", "A primeira entre 1º de fevereiro e 30 de novembro; e a segunda até 20 de dezembro"},
            {"4° graus", "2° graus", "5°graus", "3°graus"},
            {"FGTS , DSR , INSS ou IRRF", "INSS , DSR, IRRF", "INSS, FGTS e IRRF", "IRRF , FGTS, INSS"},
            {"Criado para defender o com afastamento médico", "Foi criado com o objetivo de proteger o trabalho demitido sem justa causa", "Proteger as trabalhadoras com licença maternidade", "Defender os trabalhadores demitidos com justa causa"},
            {"1° de maio de 1950", "1° de maio de 1943", "1° de maio de 1953", "1° de maio de 1963"},
            {"Presidente Juscelino Kubitschek", "Presidente Getúlio Vargas", "Presidente José Sarney", "Presidente Tancredo Neves"},
            {"A Constituição garante aos povos indígenas o direito de demarcação de terras", "A Constituição estipula que se os votos nulos alcançarem mais de 50% dos votos , a eleição presidencial é anulada, e uma nova eleição deve ser organizada em até 120 dias com novos candidatos", "A Constituição coloca como dever do Estado a defesa do meio ambiente", "É considerada a Constituição mais democrática da história do Brasil"},
            {"3 meses", "1 ano", "6 meses", "2 anos"},
            {"60 dias e só poderá ter duas prorrogações", "70 dias, tendo quantas prorrogações forem necessárias", "90 dias e só poderá ter uma única prorrogação", "120 dias e só poderá ter até duas prorrogações"},
            {"30 de novembro de 1977", "30 de novembro de 2017", "01 de maio de 1977", "01 de maio de 2017"},
            {"Forças, desenvolvimento, criatividade e ameaças", "Oportunidades, mapeamentos, desenvolvimento, fraquezas", "Forças, Oportunidades, Fraquezas e Ameaças", "Oportunidades, criatividade, motivação, desenvolvimento"},
            {"É o conjunto de tarefas e responsabilidades realizadas pelo empregado por meio do cargo", "É o  processo de estudo de concorrências", "É o estudo do comportamento  dos salários", "É uma ferramenta de planejamento e gestão que, visualmente, demonstra o fluxo do trabalho dentro da empresa e os seus responsáveis"},
            {"É uma representação gráfica da sequência das etapas de um processo", "É o documento que regulamenta as atividades trabalhistas", "Sua finalidade é identificar as atividades profissionais na instituição", "É uma estrutura gráfica que representa a estrutura e hierarquia da empresa"},
            {"É um plano de ação", "Comunicação organizacional e de supervisão, por exemplo, para ajudar funcionários a saber a quem se reportar, ou para auxiliar as pessoas a conhecerem umas às outras em uma empresa", "É uma ferramenta de planejamento e gestão que, visualmente, demonstra o fluxo do trabalho dentro da empresa e os seus responsáveis", "Especificar e identificar todas as ocupações no mercado de trabalho"},
            {"É um treinamento feito em prol do  desenvolvimento do corpo", "É o conjunto de práticas que as empresas adotam para capacitar seus colaboradores a curto e longo prazo", "São treinamentos feitos para um autodesenvolvimento", "São práticas feitas para o desenvolvimento pessoal e econômico"},
            {"Aprender a praticar esportes", "Capacitar seu cérebro", "Integrar e qualificar a equipe de modo que as entregas tenham um alto padrão de qualidade", "Ensinar exclusivamente como praticar exercícios físicos"},
            {"Treinamento de integração ou onboarding.\n" +
                    "Treinamento comportamental ou soft skill.\n" +
                    "Treinamento técnico ou hard skill.\n", "Treinamento Acadêmico \n" +
                    "Treinamento Natalino\n" +
                    "Treinamento Festival.\n", "Treinamento Formatura\n" +
                    "Treinamento coreografia\n" +
                    "Treinamento Comercial.\n", "Treinamento Musical\n" +
                    "Treinamento Pessoal\n" +
                    "Treinamento Passarela.\n"},
            {"Totalidade e Dinheiro", "Trauma e Dor", "Temática e Densidade", "Treinamento e desenvolvimento"},
            {"Departamento Pessoal", "Administração", "Recursos Humanos", "Logística"},
            {"Ajuda as pessoas no treino da academia", "Criar processos para melhorar o clima", "Preparar manuais e materias para treinamento interno e divulgar cursos e palestras", "Busca aperfeiçoar o desempenho pessoal dos colaboradores"},
            {"Habilidades e conhecimentos técnicos", "Habilidades comportamentais", "Competências subjetivas difíceis de avaliar", "Um termo que não significa nada"},
            {"Investir no desenvolvimento do profissional individual", "Capacitar exclusivamente para oportunidades futuras", "Treinar o próprio corpo", "Capacitar o cérebro"},
            {"Deixar o colaborador entusiasmado e proativo", "Diminuir a produção", "Treinar o próprio corpo", "Aumentar o nível de estress"},
            {"Dados pessoais, objetivo, formação acadêmica, experiência profissional, formação complementar, informações adicionais", "Formação acadêmica, dados pessoais, objetivo", "Somente objetivo, experiência profissional e dados pessoais", "Dados pessoais, formação complementar"},
            {"Pediria demissão", "Pediria ajuda", "Pediria mais tempo", "Ficaria tranquilo"},
            {"Ética pessoal", "Ética profissional", "Caráter profissional ", "Caráter pessoal"},
            {"Vendo a carteira de trabalho", "Contrato de trabalho", "Visualizando a crachá", "Perguntando ao colaborador"},
            {"Entrevistado pergunta e entrevistador pergunta", "Entrevistando pergunta e entrevistador responde", "Entrevistador responde e entrevistado responde", "Entrevistador pergunta e entrevistado responde"},
            {"CTPS", "Carta de referência", "Currículos", "Documentos pessoais"},
            {"Maior custo benefício", "Desempenho", "Diversidade", "Menor custo benefício"},
            {"Avaliar a comunicação dos candidatos", "Chegar ao objetivo final", "Avaliar o desempenho individual do candidato", "Todas as alternativas acima"},
            {"Avaliar a falta de comunicação entre os candidatos", "Traçar o perfil comportamental de cada um", "Uma maneira de descontrair os participantes", "Promover o conhecimento entre os candidatos"},
            {"Desenvolvimento da equipe", "Individualidade", "Liderança ", "Poder de persuasão"},
            {"Vídeo currículo", "LinkedIn", "Canva", "Google Meet"},
            {"Aparelho eletrônico, ambiente adequado e roupa de banho", "Ambiente adequado, aparelho eletrônico e caixa de som", "Aparelho eletrônico, ambiente adequado e vestimentas corretas", "Vestimentas corretas, aparelho eletrônico e a mãe"},
            {"Gravar um vídeo ensinando a fazer um currículo", "Dar mais espaços para os candidatos contarem com um pouco mais de detalhes suas competências e experiências no mercado de trabalho", "Ler o seu currículo em forma de um vídeo", "Apresentar uma empresa em um vídeo"},
            {"Uma apresentação curta e direta sobre uma empresa ou/e projeto", "Uma apresentação longa e duradoura", "Um tipo de palestra motivadora", "Uma aula pra empresas"},
            {"Washington", "Los Santos", "Barcelona ", "Hollywood "}


    };

    public static String correctAnswers[] = {
            ///respotas certas
            "São diagramas que relacionam diferentes informações a uma fonte central",
            "É uma representação gráfica da divisão hierárquica e da relação superior-subordinado",
            "Externo, interno e misto",
            "Para os aprendizes que estão cursando o ensino fundamental será seis horas diárias.Já para os que completaram o ensino médio será até 8 horas diárias",
            "14 a 24 anos",
            "Não, com a reforma trabalhista vieram mais de 100 mudanças",
            "A legislação trata sobre os direitos para com a proteção da saúde do colaborador",
            "Surgiu em 1833",
            "Alemanha",
//            pergunta abaixo não está acertada
            "alinhar com a 110",
            "Remunerada ou então voluntária",
            "São leis e regras que regem a relação entre colaboradores e empregadores",
            "Folga em todos os feriados",
            "Deve ser pago no começo do mês que ele entrar de férias",
            "Sim, para os trabalhadores com jornada superior à 6 horas diária é obrigatório o intervalo mínimo de 1hora de almoço",
            "Após 12 meses trabalhados",
            "2 dias antes do início das férias",
            "o empregador é quem define",
            "Segurança e saúde do trabalho",
            "Documento que comprova o vínculo legal entre um empregador e um colaborador",
            "Até no máximo 2 anos",
            "Descanso Semanal Remunerado",
            "Poderão ser convertidos em apenas 10 dias",
            "Gerência de Gestão de Pessoas",
            "No máximo, até 2 dias úteis antes do início do período de descanso",
            "12 meses",
            "30 dias",
            "828,38 R$",
            "90,90 R$",
            "6 %",
            "Imposto de Renda Retido na Fonte",
            "É a soma do salário e dos benefícios recebido pelo colaborador menos os descontos",
            "40 %",
            "7,5, 9, 12 e 14%",
            "A partir de 32 faltas",
            "Descanso Semanal Remunerado",
            "Instituto Nacional do Seguro Social",
            "30 dias",
            "A cada 07 dias trabalhados",
            "12 Meses de prestação de serviço",
            "10%, 20% e 40%",
            "A primeira entre 1º de fevereiro e 30 de novembro; e a segunda até 20 de dezembro",
            "3°graus",
            "INSS, FGTS e IRRF",
            "Foi criado com o objetivo de proteger o trabalho demitido sem justa causa",
            "1° de maio de 1943",
            "Presidente Getúlio Vargas",
            "A Constituição estipula que se os votos nulos alcançarem mais de 50% dos votos , a eleição presidencial é anulada, e uma nova eleição deve ser organizada em até 120 dias com novos candidatos",
            "2 anos",
            "90 dias e só poderá ter uma única prorrogação",
            "30 de novembro de 1977",
            "Forças, Oportunidades, Fraquezas e Ameaças",
            "É o  processo de estudo de concorrências",
            "É uma estrutura gráfica que representa a estrutura e hierarquia da empresa",
            "É uma ferramenta de planejamento e gestão que, visualmente, demonstra o fluxo do trabalho dentro da empresa e os seus responsáveis",
            "É o conjunto de práticas que as empresas adotam para capacitar seus colaboradores a curto e longo prazo",
            "Integrar e qualificar a equipe de modo que as entregas tenham um alto padrão de qualidade",
            "Treinamento de integração ou onboarding.\n" +
                    "Treinamento comportamental ou soft skill.\n" +
                    "Treinamento técnico ou hard skill\n",
            "Treinamento e desenvolvimento",
            "Recursos Humanos",
            "Preparar manuais e materias para treinamento interno e divulgar cursos e palestras",
            "Habilidades e conhecimentos técnicos",
            "Investir no desenvolvimento do profissional individua",
            "Deixar o colaborador entusiasmado e proativo",
            "Dados pessoais, objetivo, formação acadêmica, experiência profissional, formação complementar, informações adicionais",
            "Ficaria tranquilo",
            "Ética pessoal",
            "Visualizando a crachá",
            "Entrevistador pergunta e entrevistado responde",
            "CTPS",
            "Menor custo benefício",
            "Avaliar a comunicação dos candidatos",
            "Traçar o perfil comportamental de cada um",
            "Individualidade ",
            "Vídeo currículo",
            "Aparelho eletrônico, ambiente adequado e vestimentas corretas",
            "Dar mais espaços para os candidatos contarem com um pouco mais de detalhes suas competências e experiências no mercado de trabalho",
            "Uma apresentação curta e direta sobre uma empresa ou/e projeto",
            "Hollywood "
    };

    public QuestionsRH(){}

}
